# Generated by Django 2.1.4 on 2018-12-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(null=True, to='users.Hobbies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_connections',
            field=models.ManyToManyField(null=True, related_name='_profile_profile_connections_+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_requests',
            field=models.ManyToManyField(null=True, related_name='_profile_profile_requests_+', to='users.Profile'),
        ),
    ]
