# Generated by Django 2.1.4 on 2018-12-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181209_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(to='users.Hobbies'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_connections',
            field=models.ManyToManyField(related_name='_profile_profile_connections_+', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_requests',
            field=models.ManyToManyField(related_name='_profile_profile_requests_+', to='users.Profile'),
        ),
    ]
